---
- name: Install memcached server
  apt: pkg=memcached state=installed update-cache=yes
  tags:
    - packages

- name: Install configuration file
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify: restart memcached
  tags:
    - configuration
